POST http://localhost/Cryptographp/encrypt/ HTTP/1.1
content-type: application/json

{
    "text": "github-viniciusanchieta"
}

###
POST http://localhost/Cryptographp/decrypt/ HTTP/1.1
content-type: application/json

{
    "encrypt": "+S8w8A74n34IV43kz035KJ0VYQ5CGohLxgEzfxuG5IQlIrNOtoAsLrb0Mn3SQRepbC\/ItlSHvZShxs2a7RXYYmmgI\/e4cd+d+L8De9czM0A="    
}
